### ISSUE TITLE
Not able to get the environment

### ISSUE THREAD

**Issue by QAInsights** [dogger/app.dogger.io#726]
Hi,

I am trying a sample repo to test Pull Dog. This is my [repo](https://github.com/QAInsights/windows-docker-jmeter). I have configured the pull-dog json as mentioned in the docs. But I am not getting any environment provisioned.
Could you please help me out? Thanks!
```
{"isLazy":false,"dockerComposeYmlFilePaths":["docker-compose.yml"],"expiry":"00:00:00","conversationMode":"singleComment"}
```

Trace ID
643ff680-fd3c-11ea-9c0f-b4cd4be14fbd

**Comment by ffMathy** [comment]
Hi QAInsights! That's very unfortunate.

I'll look into it right away! If we don't make this work, we can always refund you fully (but hopefully it won't have to come to that).

**Comment by ffMathy** [comment]
Also, rest assured you don't have to do anything further at this point. I'll investigate why it's not working with your repository, and make a fork of your project to verify that it is working.

**Comment by ffMathy** [comment]
There is indeed something funky going on according to the logs. I suspect our provisioning service did not start up properly. I have added more logging in https://github.com/dogger/app.dogger.io/commit/69d48de06c92503e5b2df69aece714970c2f37e6 which will hopefully help nail the issue.

That being said though, I also noticed that your container is a Windows container. That's currently not supported unfortunately. So even if the provisioning service worked, only a Linux-based image would launch properly on Pull Dog 🙁

**Comment by QAInsights** [comment]
@ffMathy many thanks for the investigation. Let me try it in the Linux container.

**Comment by ffMathy** [comment]
Feel free! Let me know your findings once done.

**Comment by QAInsights** [comment]
@ffMathy Here is the Linux container repo. I do not see the provisioning. Could you please check [this repo?](https://github.com/QAInsights/PullDog-Demo/pull/1)

**Comment by ffMathy** [comment]
The environment is indeed provisioning!

However, since your Docker Compose file does not expose any ports, it doesn't know what connection details to post, as it also says in the comment:
> However, it doesn't seem to have any ports exposed. Make sure the Docker Compose YML contents expose a port.

This means that you'll need a `ports:` section in your YML file, if that makes sense?

**Comment by ffMathy** [comment]
Or perhaps JMeter is not an app that exposes ports? Can you tell me more about it?

**Comment by QAInsights** [comment]
@ffMathy that's correct. JMeter doesn't expose any ports. It just runs the test.

**Comment by ffMathy** [comment]
What kind of test is this? And integration or unit test?

**Comment by QAInsights** [comment]
@ffMathy It is a performance test.

**Comment by ffMathy** [comment]
Then I don't think Pull Dog is for you. Perhaps you should look in to GitHub Actions instead, or a build server?

Pull Dog is designed to make temporary test environments for each pull request, so that the review phase of a pull request becomes faster and simpler. It doesn't try to compete with job runners or CI environments, which seems to be what you are looking for?

Or perhaps I'm misunderstanding?

**Comment by QAInsights** [comment]
Thanks @ffMathy I already developed a GitHub Action to run performance tests. Please check [here](https://github.com/QAInsights/PerfAction). GitHub Action requires some initial effort. I think Pull Dog can fulfill this. Spin up a test environment, share the results, and delete the instance. Thoughts?

**Comment by ffMathy** [comment]
Hmmm. I could make it post the amount of time that the container was running for, when it shuts down?

Would that work for you?

**Comment by QAInsights** [comment]
Is it possible to copy the contents to the GitHub repo after container shuts down? I want to extract the results of my performance testing?

**Comment by ffMathy** [comment]
With all due respect, I think there is a better way to do this.

Have you considered running the tests on GitHub Actions, and then post the results to Graphite, and put a Grafana server in front of it?

I'm afraid what you're requesting is a bit outside the desired target audience of Pull Dog.

I'm closing the issue, but let's keep the discussion going. Perhaps I can still help you!

**Comment by QAInsights** [comment]
@ffMathy as you mentioned, I have already implemented similar solution :). I stumbled upon Pull Dog, just want to explore the feasibility for performance testing.

**Comment by ffMathy** [comment]
Ah I understand. Thank you for trying it out either way! 🙏
