### ISSUE TITLE
Unable to provision new environments

### ISSUE THREAD

**Issue by deviantony** [dogger/app.dogger.io#786]
For the last couple of days, pull-dog is not deploying our envs and stay in the state "environment is on its way".

See https://github.com/portainer/portainer/pull/4373 for reference.

**Comment by ffMathy** [comment]
That's not good! I'll issue a full refund for the month and try to fix the issue tomorrow morning!

I'm sorry this happened. I'll go through the logs looking for a potential cause!

**Comment by deviantony** [comment]
Thanks for the quick update :)

**Comment by ffMathy** [comment]
Apparently the queue for your account had gotten in an invalid state somehow.

While I haven't fixed the issue, I have improved logging significantly in https://github.com/dogger/app.dogger.io/commit/16777be0b2741e761d381639dd6eed371f27f427, to be able to find the issue in the future. As soon as I redeployed the logging change, the problem could not longer be reproduced.

This unfortunately means that the issue *will happen again*, but this time I'll have more details to fix it!

I'll leave the issue open as a reminder. Please report back if you see it again! I'll also check the Portainer activity myself once in a while, but I can't do that every day.

I hope this is acceptable to you, and I understand the frustration of this potentially happening again.

**Comment by deviantony** [comment]
Allgood @ffMathy I'll keep you posted in this issue if the issue arises again.
